CircleCI-Public/docker-orb

src/commands/build.yml
src/jobs/publish.yml

Fixes #2 
Add `registry` parameter to `build` command to match `push` command, enabling the `publish` job to work with 3rd party registries.

Add registry parameter to build command

---

src/commands/push.yml
src/examples/build-push-digest.yml

Docker images in a registry have an immutable identifier generated by
the registry using a hash of the image manifest. This is very useful
for identifying an exact image.
This digest is returned by the registry when an image is pushed and
added to the local image metadata by the docker engine, which is our
opportunity to save it.
See https://success.docker.com/article/images-tagging-vs-digests
Specifically, this will let you use the digest when deploying an image and
avoid any problems with mutable tags.
Add the `digest-path` parameter to `push` command.
This parameter can be used to save the digest of an image to a file.
Subsequent commands can read this file to use the digest. The contents of the file looks like:
```
my_repo/orb-test@sha256:07891cedde37fd3719fd40aa3b5ad722a86b9abf8e06e99 …
```

Add digest-path parameter to push command

---

.circleci/config.yml
src/commands/build.yml
src/commands/pull.yml
src/examples/custom-pull.yml
src/examples/with-cache-from.yml
src/jobs/publish.yml

This is a redo of #16 - with all of the same changes but minus the messy history. I was upset that the work got messy, and wanted the changes to be represented in one clean commit, and am doing that here. 
@KyleTryon as noted in previous discussion, I've added the docker pull to be done by build, which is the command done by publish, so a user doing a custom build step will still get it. The pull command is also added as a separate command. It may be trivial to do, but it seems like it could still be useful and read nicely in some custom pipeline. Instead of needing three lines for three docker pull commands, you just add the list of comma separated containers!
----------------------------------------------------------------
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
I've had …

Adding cache_from argument

---

src/commands/build.yml
src/commands/pull.yml

When ignoring docker pull errors, allow pulling the rest of the images if one fails to be pulled

Fix `docker@0.5.15`: allow pull to continue for rest of the images after a pull error

---

src/commands/install-docker.yml

If user has a directory named `docker` in their workspace/repository, it would be manipulated unnecessarily by `install-docker-tools`. This can be avoided by using a temporary download directory for Docker binaries.
Closes #13 
- Fix install-docker-tools moving workspace files
- Don't download Docker binaries into the workspace but into a temporary directory
- Don't attempt to remove directories named "docker" inside the workspace

Fix install-docker-tools moving workspace files

---

.circleci/config.yml
src/commands/build.yml
src/commands/push.yml
src/examples/with-multiple-tags.yml
src/jobs/publish.yml

See issue #36 - it's currently not possible to build or push images using multiple tags (with a single command).
- Change docker build and push commands to iterate over a comma-separated list of tags
- Update README to reflect these changes
- Add integration test step to cover case with multiple tags

Add support for build/push using multiple tags

---

src/commands/build.yml

https://github.com/CircleCI-Public/docker-orb/pull/38 introduces multi-tag builds but there are some nitpicky bash syntax / linebreak issues causing jobs to fail... this fixes them, also adds a step name for the `docker build` command, to make output in the UI nicer

Fix multi tag builds

---

src/commands/dockerlint.yml

`dockerlint` command currently has documentation referencing `hadolint`, instead of `dockerlint`, as noted by @jeff-knurek (https://github.com/CircleCI-Public/docker-orb/issues/40)
update documentation to correctly apply to `dockerlint`

Fix dockerlint command documentation

---

src/examples/custom-name-tag-executor.yml

We've added the ability to specify DLC for this orb's `publish` job,
when using a Docker-based executor; add an example to note this
functionality.

Add DLC to Docker executor example

---

src/commands/update.yml
src/examples/build-without-updating.yml
src/examples/custom-readme-file.yml
src/examples/standard-build-and-push.yml
src/jobs/publish.yml

This PR closes #46
This PR adds an `update` command which update's an image's description to the contents of `README.md` when publishing to Docker Hub. The publish job has been modified to run the update command as well.
I've also added parameters to provide a custom README file as well as disable updating the description. Currently, descriptions are updated by default.
I'm not sure of the best way to test these changes in CI, but I manually tested them and they appear to be functioning as intended.

Add update description command

---

.circleci/config.yml
src/commands/install-docker-compose.yml

- Update the pipeline to use the new orb tools orb version
- Resolve https://github.com/CircleCI-Public/docker-orb/issues/51 . The `install-docker-compose` command is failing (and making the pipeline fail), for the latest docker-compose releases (e.g. `1.25.4`) see: https://circleci.com/gh/CircleCI-Public/docker-orb/3228 . The failure is because the current `install-docker-compose` command uses the sha256 sum available in the GitHub Releases API response body (e.g. https://github.com/docker/compose/releases/tag/1.25.1), but for newer releases, the sha256 sum is not available in the response body (e.g. https://github.com/docker/compose/releases/tag/1.25.3) The resolution here is to download the sha256 file first and only fall back to using the current method of checking the response body …

Fix install-docker-compose shasum verification [semver:patch]

---

.circleci/config.yml
src/@orb.yml
src/commands/check.yml
src/commands/configure-docker-credentials-store.yml
src/commands/install-docker-credential-helper.yml
src/examples/login-with-credentials-store.yml
src/jobs/publish.yml

When `docker login` is done without a credentials store configured, the command returns a warning:
```
docker: WARNING! Your password will be stored unencrypted in /home/circleci/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```
This warning has high impact for Azure ACR usage. In the latest version of the Azure client, the `az acr login` command returns an error if a credentials store is not used: (See: https://github.com/CircleCI-Public/azure-acr-orb/issues/11)
```
#!/bin/bash -eo pipefail
az acr login --name azureacrorb
Login Succeeded
docker: WARNING! Your password will be stored unencrypted in /home/********/.docker/config.json.
Configure a credential helper to remove this …
```

Add commands for docker credentials store usage [semver:minor]

---

src/commands/build.yml

Fixes #52.
Leverage `<<parameters.step-name>>` instead of hard-coded value.

fix: respect step-name parameter in build command [semver:patch]

---

src/jobs/hadolint.yml

Resolves https://github.com/CircleCI-Public/docker-orb/issues/17
Marking this as major because the removal of the `artifacts-path` parameter will break builds that specified it

Remove artifacts-path parameter and store_artifacts step from hadolint job [semver:major]

---

src/commands/push.yml

When providing both multiple tags and a digest path in `docker/push`,
the digest lookup would previously fail with `invalid reference format`
as it would append all the tags. 
[Here is an example of this bug](https://app.circleci.com/pipelines/github/agilepathway/cimg-gauge/109/workflows/a8534681-9984-4de8-8711-6c446bf1ec96/jobs/294) manifesting itself, caused by having [both multiple tags and a digest path specified](https://github.com/agilepathway/cimg-gauge/commit/6de0a4bcea736f8347ea9b01bec2b42b1ff66882), e.g:
```
- docker/push:
digest-path: /tmp/digest
image: agilepathway/cimg-gauge-multiple-tags
tag: 'tag1,tag2'
```
Fix bug in `docker/push` command when specifying both of the following together:
1. multiple tags
2. digest path
Fix by now always using the first provided tag for the …

Fix bug when multiple tags and digest path present

---

src/commands/push.yml

Reverts CircleCI-Public/docker-orb#62

Revert "Fix bug when multiple tags and digest path present" (#71) [skip ci]

---

.circleci/config.yml
src/jobs/hadolint.yml

When I used hadolint job with multiple tilde-prefixed Dockerfile paths as the dockerfiles parameter, _No such file or directory_ error occurred.
```
DOCKERFILES=~/project/frontend/Dockerfile,~/project/worker/Dockerfile
...
Running hadolint with the following options...
Success! /root/project/frontend/Dockerfile linted; no issues found
hadolint: ~/project/worker/Dockerfile: openBinaryFile: does not exist (No such file or directory)
```
According to [the bash manual](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html), _Each variable assignment is checked for unquoted tilde-prefixes immediately following a ‘:’ or the first ‘=’_. So, we should use colons instead of commas.
Change comma delimiters to colons in hadolint job's dockerfiles parameter.

[semver:minor] Use colon delimiters in hadolint dockerfiles parameter

---

src/commands/build.yml
src/commands/install-docker-compose.yml

Part of https://github.com/CircleCI-Public/gcp-gcr-orb/issues/41
Add no_output_timeout param for Docker image build and update python install on alpine by switching to python3.

Add no_output_timeout parameter for docker build timeout and update python install on alpine [semver:minor]

---

.circleci/config.yml
src/commands/install-docker-compose.yml
src/commands/update-description.yml
src/examples/hadolint.yml
src/jobs/hadolint.yml

extends pr #81 by @yaningo with required updates
Motivation, issues
When using the orb's hadolint job, it's not currently possible to specify the hadolint image tag or the resource_class to use, as defined in the orb's hadolint executor.
Description
Add pass-through parameters hadolint-tag and executor-class to the hadolint job so users can override the hadolint executor default parameters.
This pull-request resolves #80.
---
What this patch-pr provides to the original:
- Replace Docker Auth
- Fix Alpine tests by updating pip before installing Docker-Compose

Patch pr/81 [semver:minor]

---

.circleci/config.yml
src/commands/hadolint.yml
src/jobs/hadolint.yml

Technically no breaking changes but does include a new command.
closes #42

[semver:minor] Split hadolint into own command.

---

src/executors/machine.yml

- Updated default image to the latest Ubuntu image

[semver:major] Updated default image to ubuntu-2004:202107-02

---

src/commands/pull.yml

The pull command is missing a name, resulting in a weird display on the CircleCI GUI.
This adds a name to the pull command

[semver:patch] Add missing name on pull command

---

src/commands/build.yml

Improve quality.
Fixes a minor typo in the description of the `build` command.

Fix typo in the build command description

---

src/executors/docker.yml

When using the docker executor, a warning is displayed on CircleCI:
```
You’re using a deprecated Docker convenience image. Upgrade to a next-gen Docker convenience image.
```
See https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
Replace deprecated circle/docker image with the next-gen on cimg/docker.

Use next-gen Docker convenience image

---

.circleci/config.yml

As part of CPE-554 we want to cut down usage of the old Xcode 10.3 image as much as possible

Bump "macos-old" version

---

src/commands/install-docker-compose.yml

In the [2.5.0 release](https://github.com/docker/compose/releases/tag/v2.5.0), The Docker Compose checksum is [now calculated with the `--binary` flag](https://github.com/docker/compose/pull/9389), causing a leading asterisk to be added to the filename in the output.

Fix parsing filename out of checksum

---

src/commands/push.yml
src/scripts/push.sh

New PRs are failing the review step because the push command has bash in it. Even though the script was extracted in #120, the code was never replaced with it.
Replace the bash code with an import containing the script path.

fix: import the `push.sh` script in the push command

---

src/commands/push.yml
src/commands/update-description.yml

Updates `deploy` steps to use `run` instead.
Resolves https://github.com/CircleCI-Public/docker-orb/issues/128
I was able to verify that compiled Orb is valid:
```console
$ circleci orb process src/@orb.yml > orb.yml
$ circleci orb validate orb.yml
Orb at `orb.yml` is valid.
```
I checked that the `update-description` command is also tested under the `publish-docker-update-description` test case.
example: https://app.circleci.com/pipelines/github/CircleCI-Public/docker-orb/796/workflows/92fbd710-d32d-492a-b4e0-79362afef857/jobs/13674

fix: replace `deploy` steps to `run`

---

src/commands/update-description.yml
src/scripts/update-description.sh

The Docker Hub API only supports `application/json` now. This PR changes the `update-description` command to send JSON in the request body instead of `x-www-form-urlencoded`.
- Closes #138
Changes the Docker Hub API request to send a JSON payload (#138). Thank for the suggestion, @zigarn!

fix: payload used in the update description request

---

src/@orb.yml
src/commands/check.yml

The orb's dependencies were outdated.
Bump `jq` and `build-tools` and remove `orb-tools` and its commands.

chore: bump orb dependencies and remove deprecated commands

---

.circleci/test-deploy.yml
src/commands/install-docker-compose.yml
src/scripts/install-docker-compose.sh

The latest release (v2.10.0) of Docker Compose does not have `sha` files. This makes the `install-docker-compose` command fail with a 404 error from `curl`.
- Closes #140
With this change, compose releases coming with the `checksums.txt` will have their integrity verified with it. Otherwise, the `.sha256` will be used instead.

fix: curl error in `install-docker-compose`

---

.circleci/test-deploy.yml
src/scripts/push.sh

Ever since the shell code in YAML was replaced with its dedicated file in #131, the `publish` job lost support for environment variables in the `image` parameter. This PR will bring back support.
- Closes #136
- Closes #139 
Variable expansion via `eval echo` was included in all pertinent scripts. And a new test was included in the suite to cover this use case (#136, #139).

fix: support for env vars parameters in `publish`

---

src/scripts/build.sh

Fixes #137 
Support expanding env vars on the `extra_build_args` parameter.

Support expanding env vars on the extra_build_args parameter

---

.circleci/test-deploy.yml
src/scripts/build.sh
src/scripts/hadolint.sh
src/scripts/install-docker-credential-helper.sh

Closes #154 
- Change the download URL based on the release's minor version.
- Add tests for release tags other than the latest

fix: error when downloading the credential helper's latest version

---

.circleci/test-deploy.yml
src/commands/build.yml
src/commands/check.yml
src/commands/configure-docker-credentials-store.yml
src/commands/dockerlint.yml
src/commands/hadolint.yml
src/commands/install-docker-compose.yml
src/commands/install-docker-credential-helper.yml
src/commands/install-docker.yml
src/commands/install-dockerize.yml
src/commands/install-goss.yml
src/commands/pull.yml
src/commands/push.yml
src/commands/update-description.yml
src/scripts/build.sh
src/scripts/check.sh
src/scripts/configure-docker-credentials-store.sh
src/scripts/dockerlint.sh
src/scripts/hadolint.sh
src/scripts/install-docker-compose.sh
src/scripts/install-docker-credential-helper.sh
src/scripts/install-docker.sh
src/scripts/install-dockerize.sh
src/scripts/install-goss.sh
src/scripts/pull.sh
src/scripts/push.sh
src/scripts/update-description.sh
src/scripts/utils.sh

Due to the Orb Tools 11 migration, the orb no longer supports environment variables as parameters. The reason behind it is explained in detail [here](https://github.com/CircleCI-Public/docker-orb/issues/135#issuecomment-1159137531). 
While the parameters were not meant to support environment variables unless their type is `env_var_name`, we see an increasing number of issues, such as #151, requesting the functionality back.
This PR leverages the utility function introduced in the [gcp-gke-orb](https://github.com/CircleCI-Public/gcp-gke-orb/pull/57) to expand all variables coming from parameters. Soon, we will introduce a better way of importing and running such functions. When it happens, I'll refactor the changes introduced here.

fix: evaluate and expand all orb parameters

---

.circleci/test-deploy.yml
src/commands/hadolint.yml
src/scripts/hadolint.sh

Currently if the `docker/hadolint` command is used with an `executor` other than the `hadolint` docker image, the  command fails. This `PR` installs hadolint if it isn't already.

fix: install hadolint for hadolint command

---

src/executors/machine.yml

This `PR` updates the default image for the `machine` executor to support `arm64` it also adds the `resource-class` parameter to the executor as well.

feat: update default image to support arm resource class

---

.circleci/test-deploy.yml

The `macos-old` executor used in this orb's tests was sunsetted. Unfortunately we cannot use M1 executors at the moment because the orb does not support multi-arch.

fix: macOS test executors

---

src/scripts/build.sh

The --progress flag is not supported on the more recent Windows machine builds

Remove --progress flag since it doesn't work for recent Windows

---

.circleci/test-deploy.yml
src/commands/build.yml
src/commands/check.yml
src/commands/install-docker-credential-helper.yml
src/examples/with-cache-to.yml
src/jobs/publish.yml
src/scripts/build.sh
src/scripts/install-docker-credential-helper.sh
test4.Dockerfile

I'm adding a new parameter to allow cache_to similar to the cache_from option.
I'm also updating the orb and tests to support new Mac Silicon and ARM architectures.

Add cache_to option in the build and publish commands

---

.circleci/test-deploy.yml
src/jobs/publish.yml

Currently defined version is not available since end of September

Use latest docker for remote machine

---

src/scripts/build.sh

We want to be able to use environment variables in cache_to parameter.
Eval cache_to parameter

feat: eval cache_to parameter to allow to use variables

---

src/scripts/build.sh

There is no need to manually pull cache_from image, buildx does it on its own. 
Remove manual cache_from image pull

feat: no need to pull cache_from image
