CircleCI-Public/docker-orb

.circleci/config.yml
src/commands/install-docker-tools.yml
src/examples/install-docker-tools.yml

provide a simpler way to install all docker tools in one command
`install-docker-tools` command runs `install-docker`, `install-docker-compose`, and `install-dockerize`

All in one command

---

.circleci/config.yml

test install-docker-tools command against oracle linux: https://discuss.circleci.com/t/convenience-images-update-add-our-convenience-image-tooling-to-your-own-docker-images-with-orbs
no new orb stuff, everything already works, just add tests in config. shouldn't publish a new version at all.

test against oracle

---

.circleci/config.yml
src/commands/dockerlint.yml
src/examples/lint-dockerfile.yml

we want to easily lint Dockerfiles (others probably do too)
add `dockerlint` command that installs and runs [Dockerlint](https://github.com/redcoolbeans/dockerlint)

[CIRCLE-19332] Add `dockerlint` command

---

.circleci/config.yml
src/commands/dockerlint.yml
src/examples/hadolint.yml
src/executors/hadolint.yml
src/jobs/hadolint.yml

add more recently updated, more configurable, easier-to-use Dockerfile linter
- add hadolint executor
- add hadolint job

[CIRCLE-19332] Add hadolint executor/job

---

.circleci/config.yml
src/commands/build.yml
src/commands/push.yml
src/examples/with-multiple-tags.yml
src/jobs/publish.yml

https://github.com/CircleCI-Public/docker-orb/pull/37

Add support for build/push using multiple tags => master

---

.circleci/config.yml
src/jobs/publish.yml

#43 
Add `remote-docker-dlc` parameter to `jobs/publish`.

Make it able to use docker layer caching if using docker executor

---

.circleci/config.yml
.github/CODEOWNERS
src/@orb.yml
src/commands/install-docker-compose.yml
src/commands/install-docker-credential-helper.yml
src/commands/install-dockerize.yml
src/commands/install-goss.yml

Reduce GitHub API usage to avoid GitHub rate limiting errors, to help resolve https://github.com/CircleCI-Public/docker-orb/issues/59

Reduce GitHub api usage [semver:patch]

---

src/jobs/publish.yml

Remove name from when statements in publish job [semver:patch]

---

src/examples/hadolint.yml

Update hadolint.yml [semver:patch]

---

.circleci/config.yml

server:skip as this is from a test not from the orb

Remove deprecated Ubuntu 16.04 image [semver:skip]

---

.circleci/test-deploy.yml
src/commands/dockerlint.yml
src/scripts/dockerlint.sh

Closes #79.
Extract the dockerlint command to a separate script file and add the `-f` parameter to fix the bug.

fix: dockerlint command bug

---

src/commands/hadolint.yml
src/scripts/hadolint.sh

refactor: extract hadolint

---

src/commands/build.yml
src/scripts/build.sh

refactor: extract build

---

src/commands/check.yml
src/commands/configure-docker-credentials-store.yml
src/scripts/check.sh
src/scripts/configure-docker-credentials-store.sh

refactor: extract check and credentials

---

src/commands/install-dockerize.yml
src/scripts/install-dockerize.sh

refactor: extract scripts from install-dockerize

---

src/commands/install-goss.yml
src/scripts/install-goss.sh

refactor: extract scripts from install-goss

---

.circleci/config.yml
src/commands/pull.yml
src/commands/push.yml
src/commands/update-description.yml
src/scripts/pull.sh
src/scripts/push.sh
src/scripts/update-description.sh

refactor: extract scripts from pull, push and update-descriptions

---

.circleci/test-deploy.yml

The test was introduced in #121, but it wasn't included in the promotion requirements.
Add the test job to the promotion requirement list.

ci: add multiple tags test to requirements

---

.circleci/test-deploy.yml
src/@orb.yml
src/commands/check.yml
src/commands/install-docker-compose.yml
src/commands/update-description.yml
src/scripts/install-docker-compose.sh
src/scripts/push.sh
src/scripts/update-description.sh

- Closes #136
- Closes #139
- Closes #138
- Closes #140
- #142
- #143
- #145

fix: issues related to `publish`, `install-docker-compose` and `update-description`

---

src/scripts/install-docker-compose.sh

Closes #133
Remove the checksum file after the script is finished or if something goes wrong during the execution.

feat: clean-up after `install-docker-compose`

---

src/scripts/install-docker-credential-helper.sh

Update the comment to reflect what was discussed here: https://github.com/CircleCI-Public/docker-orb/pull/156#discussion_r977920812

chore: update comment to reflect dev's input

---

.circleci/test-deploy.yml
src/executors/machine.yml

feat: update image to current

---

.circleci/test-deploy.yml

Updating which cci contexts are used in tests

Change test context

---

.circleci/test-deploy.yml
src/commands/build.yml
src/executors/docker.yml
test2.Dockerfile
test5.Dockerfile

Resolves #197 
I'm updating the default executor of this orb to a newer python version, and reverting the deletion of DOCKER_BUILDKIT environment variable.
I'm also adding some extra tests that validate the --secret flag on docker args.

Fix issues with args
